# Generated by Django 3.0.6 on 2020-05-28 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desejos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeUser', models.CharField(max_length=80)),
                ('nomeLista', models.CharField(max_length=80)),
                ('url', models.URLField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('price', models.IntegerField()),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Desejos')),
            ],
        ),
    ]
