# Generated by Django 3.0.6 on 2020-05-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='minPrice',
        ),
        migrations.AddField(
            model_name='desejos',
            name='percent',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='item',
            name='priceDayAdd',
            field=models.IntegerField(default=0),
        ),
    ]
